=== dark0111/iuniv-1/css/Portfolio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="cameras">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="camera">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="model_id" type="xsd:string"/>
							<xsd:element name="model_nm" type="xsd:string"/>
							<xsd:element name="model_img" type="xsd:string"/>
							<xsd:element name="company" type="xsd:string"/>
							<xsd:element name="price" type="xsd:string"/>
							<xsd:element name="camera_type" type="xsd:string"/>
							<xsd:element name="sensor">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="sensor_type" type="sensor_type"/>
											<xsd:attribute name="pixel" type="xsd:string"/>
											<xsd:attribute name="size" type="xsd:string"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="lens">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="mount_type" type="xsd:string"/>
											<xsd:attribute name="compatibility" type="xsd:string"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="performance">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="shutter_speed" type="xsd:string"/>
											<xsd:attribute name="metering" type="xsd:string"/>
											<xsd:attribute name="live_view" type="xsd:string"/>
											<xsd:attribute name="continuous_shoting" type="xsd:string"/>
											<xsd:attribute name="video" type="xsd:string"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="lcd_size" type="xsd:string"/>
							<xsd:element name="memory_card" type="xsd:string"/>
							<xsd:element name="weight" type="xsd:string"/>
							<xsd:element name="size" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- 글로벌 데이터 타입 -->
	<xsd:simpleType name="sensor_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CCD" />
			<xsd:enumeration value="CMOS" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dark0111/iuniv-1/css/Portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<cameras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Portfolio.xsd">
	<!-- Main Element - Config Model -->
	<camera>
		<model_id>CA_0001</model_id>
		<model_nm>D300s</model_nm>
		<model_img>http://imgdc.dcinside.com/contents/goods/model/8593_d300sm.jpg</model_img>
		<company>니콘</company>
		<price>최저가:1,767,000원</price>
		<camera_type>DSLR</camera_type>
		<sensor>
			<sensor_type>CMOS</sensor_type>
			<pixel>1,230만</pixel>
			<size>23.6 x 15.8mm</size>
		</sensor>
		<lens>
			<mount_type>NIKON DX Mount</mount_type>
			<compatibility>AF-S, AF-I, AF G or D</compatibility>
		</lens>
		<performance>
			<shutter_speed>1/8000 ~ 30 sec</shutter_speed>
			<metering><![CDATA[1005분할 RGB센서에 의한 TTL개방 측광 방식
			 : 약 φ8mm 상당을 측광(중앙부 중점도 약 75%), φ6mm,φ10mm, φ13mm
			 : 3D-RGB멀티 패턴 측광II(G/D타입 렌즈 사용시), RGB멀티패턴 측광II
			 : 약φ3 mm상당(전체 화면의 약 2%)을 측광, 포커스 포인트에 연동하여 측광 위치 가동]]></metering>
			<live_view>지원 (구도 우선/ 초점 우선)</live_view>
			<continuous_shoting>7fps</continuous_shoting>
			<video>1,280 x 720(24fps) / 640 x 424(24fps) / 320 x 216(24fps)</video>
		</performance>
		<lcd_size>3인치 92만 화소</lcd_size>
		<memory_card>CF/SD/SDHC</memory_card>
		<weight>840g</weight>
		<size>147×114×74 mm</size>
	</camera>
</cameras>
